services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - Sampel-network
    restart: unless-stopped

  perplexica-backend:
    build:
      context: .  # Root directory since backend is inside src/
      dockerfile: backend.dockerfile
    image: Abhishek/Sampel-backend:main
    environment:
      - SEARXNG_API_URL=http://searxng:8080
      - DATABASE_URL=file:/home/Sampel/data/db.sqlite  # Ensures SQLite is stored properly
    depends_on:
      - searxng
    ports:
      - 3001:3001
    volumes:
      - backend-dbstore:/home/Sampel/data
      - uploads:/home/Sampel/uploads
      - ./config.toml:/home/Sampel/config.toml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - Sampel-network
    restart: unless-stopped

  Sampel-frontend:
    build:
      context: .  # Root directory
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://127.0.0.1:3001/api
        - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:3001
    image: Abhishek/Sampel-frontend:main
    depends_on:
      - Sampel-backend
    ports:
      - 3000:3000
    networks:
      - Sampel-network
    restart: unless-stopped

networks:
  Sampel-network:

volumes:
  backend-dbstore:
  uploads:
