services:
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - sampel-network
    restart: unless-stopped

  sampel-backend:
    container_name: sampel-backend
    build:
      context: .  # Root directory since backend is inside src/
      dockerfile: backend.dockerfile
    image: sampel/sampel-backend:main
    environment:
      - SEARXNG_API_URL=http://searxng:8080
      - DATABASE_URL=file:/home/sampel/data/db.sqlite  # Ensure this path is correct
    depends_on:
      - searxng
    ports:
      - 3001:3001
    volumes:
      - backend-dbstore:/home/sampel/data
      - uploads:/home/sampel/uploads
      - ./config.toml:/home/sampel/config.toml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - sampel-network
    restart: unless-stopped

  sampel-frontend:
    container_name: sampel-frontend
    build:
      context: .  # Root directory
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://sampel-backend:3001/api
        - NEXT_PUBLIC_WS_URL=ws://sampel-backend:3001
    image: sampel/sampel-frontend:main
    depends_on:
      - sampel-backend
    ports:
      - 3000:3000
    networks:
      - sampel-network
    restart: unless-stopped

networks:
  sampel-network:

volumes:
  backend-dbstore:
  uploads: