
services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - sampel-network
    restart: unless-stopped

  sampel-backend:
    build:
      context: .  # Root directory since backend is inside src/
      dockerfile: backend.dockerfile
    image: sampel/sampel-backend:main
    environment:
      - SEARXNG_API_URL=http://searxng:8080
      - DATABASE_URL=file:/home/sampel/data/db.sqlite  # Ensure this path is correct
    networks:
      - sampel-network
    depends_on:
      - searxng
    restart: unless-stopped

  sampel-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
    image: sampel/sampel-frontend:main
    environment:
      - NEXT_PUBLIC_WS_URL=ws://sampel-backend:3001
      - NEXT_PUBLIC_API_URL=http://sampel-backend:3001/api
    ports:
      - 3000:3000
    networks:
      - sampel-network
    depends_on:
      - sampel-backend
    restart: unless-stopped

networks:
  sampel-network:
    driver: bridge
